-- require("mason").setup {}
-- require("mason-lspconfig").setup { ensure_installed = { "pyright", }, }
-- require 'lspconfig'.pyright.setup {
--   settings = {
--     pyright = {
--       include = {
--          '/Users/luana.grunheidt/Git/cortex/axonius-core',
--          '/Users/luana.grunheidt/Git/cortex/adapters',
--          '/Users/luana.grunheidt/Git/cortex/axonius-libs/src/libs/axonius-py'
--       },
--       extraPaths = {
--          '/Users/luana.grunheidt/Git/cortex/axonius-core',
--          '/Users/luana.grunheidt/Git/cortex/adapters',
--          '/Users/luana.grunheidt/Git/cortex/axonius-libs/src/libs/axonius-py'
--       }
--     },
--     include = {
--        '/Users/luana.grunheidt/Git/cortex/axonius-core',
--        '/Users/luana.grunheidt/Git/cortex/adapters',
--        '/Users/luana.grunheidt/Git/cortex/axonius-libs/src/libs/axonius-py'
--     },
--     extraPaths = {
--        '/Users/luana.grunheidt/Git/cortex/axonius-core',
--        '/Users/luana.grunheidt/Git/cortex/adapters',
--        '/Users/luana.grunheidt/Git/cortex/axonius-libs/src/libs/axonius-py'
--     }
--   }
-- }
